services:
  - type: web
    name: scrapergptproplusfinal
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: bash start.sh
    repo: https://github.com/marketingtoolslat/ScraperGPTProPlusFinal
    branch: main
